### PR TITLE
Set buildpack and move cookie passphrase to environment.

### PR DESCRIPTION
**Pull request by jmcarp**
To encourage users to keep configuration in the environment rather than in files. Disclaimer: I don't know php, don't want to, and haven't tested this 😇.

### CODE REVIEW

**Review by LinuxBozo — COMMENTED** [review]
LGTM, but not sure we want to rip out guidance on editing `htdocs/sites/default/settings.php` and instead, steer them clear of the db and hash salt settings. Then again, unless you really know drupal, and your hosting environment, there is quite a bit in there that could get folks in trouble, so maybe not mentioning it is better after all.  🤷‍♂️

**Review by fureigh — CHANGES_REQUESTED** [review]
Thanks, @jmcarp! Good call on setting a good example with environment variables. Confirming: deployment still works.

As for the instructions: standard Drupal 7 installation requires modifying the settings.php file, so I'd say it's worth mentioning that in contrast, we've removed the need for the reader to do that.

Perhaps:
> Note that you do *not* need to edit the database configuration in `htdocs/sites/default/settings.php`. The file included with this example will automatically pull that information from `VCAP_SERVICES`.

If you'd rather I merge it and make that change separately, just LMK. Thanks again!

**Comment by jmcarp** [comment]
@fureigh: I don't have a clear idea of what drupal users are expecting. Could you add the language you prefer to this patch or to a follow-up?

**Comment by fureigh** [comment]
@jmcarp Yep!

**Review by fureigh — APPROVED** [review]

**Comment by fureigh** [comment]
I went ahead and incorporated that language. @LinuxBozo, if it looks good to you, I say we :shipit:.

**Comment by LinuxBozo** [comment]
Looks great. :shipit:

**Pull request merged**
