### PR TITLE
Licenses

### PR DESCRIPTION
**Pull request by pburkholder**

### CODE REVIEW

**Comment by brittag** [comment]
How did the Drupal 8 example start with GPL and switch to CC0, instead of retaining GPL? Since "without a license" means copyrighted by the original authors, can you ask upstream for the original authors to apply a license to the upstream work so we can inherit that license?

**Comment by pburkholder** [comment]
I've suggested an Apache license upstream, https://github.com/cloudfoundry-samples/cf-ex-drupal/pull/6

I thought the GNU license was just a default license inserted by PHP Composers (https://getcomposer.org/doc/04-schema.md#license), but I was mistaken as the LICENSE is delibrately set to GNU (https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L5)

So I should probably say that our contributions are CC0, the base project is GNU, as we do for cf-ex-wordpress, https://github.com/18F/cf-ex-wordpress/blob/master/LICENSE.md

**Comment by pburkholder** [comment]
Reverted Drupal 8 license to GNU, we clarification in README that this project to enable running in cloud.gov is CC0.

**Comment by brittag** [comment]
Thanks, this looks good to me!

**Review by brittag — APPROVED** [review]

**Pull request merged**
